services:
  elasticsearch:
    image: elasticsearch:8.15.5
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      #- ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-}
    networks:
      - elastic-network
    volumes:
      - data_elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always

  kibana:
    image: kibana:8.15.5
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      #- ELASTICSEARCH_USERNAME=kibana_system
      #- ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    networks:
      - elastic-network
    volumes:
      - data_kibana:/usr/share/kibana/data
    ports:
      - 5601:5601
    restart: always
